version: "3.7"
services:
  app:
    build: app
    ports:
      - $host_port:80
    networks:
      default:
        aliases:
          - "test-backend"
    environment:
      - ASSERTS=true
      - APP_REPO_LINK=/tmp/test_repo.git
    volumes:
      - $target_repo:/app/repo-store/repo
      - $target_ssh_keys:/root/.ssh
      - /tmp/test_repo.git:/tmp/test_repo.git
      # - /tmp/server_side_tmp:/tmp # contains archives of revisions
  tests:
    build: tests
    volumes:
      - ./build_artifacts:/app/reports
      - $target_repo:/app/repo
      - /tmp/test_repo.git:/tmp/test_repo.git
      # - /tmp/tests_tmp:/tmp # contains archives of reveived revisions
    networks:
      - default  

networks:
  default:    
