version: "3.7"
services:
  app:
    build: app
    ports:
      - $host_port:80
    networks:
      default:
        aliases:
          - "test-backend"
    environment:
      - ASSERTS=false
    volumes:
      - $target_repo:/app/repo-store/repo
  tests:
    build: tests
    volumes:
      - ./build_artifacts:/app/reports
      - $target_repo:/app/repo
    networks:
      - default  

networks:
  default:    
