version: "3.7"
services:
  app:
    build: app
    ports:
      - 80:80
    networks:
      default:
        aliases:
          - "test-backend"
    environment:
      - ASSERTS=false
    volumes:
      - ./tests/test_repo:/app/repo-store/repo
  tests:
    build: tests
    environment:
      - HEAD_COMMIT=$head_commit
    volumes:
      - ./build_artifacts:/app/reports
    networks:
      - default  

networks:
  default:    
